### ISSUE TITLE
Rules in .eslintrc

### ISSUE THREAD

**Issue by eridal** [labs-js/turbo-git-log#4]
There are many rules in `.eslintrc` and some of them are breaking both bitHound checks and my local box.

I know this is a matter of taste and I'm really unopinionated regarding what rules to pick, but if I were to chose them, this is what I'd use as a tidy baseline 

```json
{
  "extends": "eslint:recommended",
  "env": {
    "node": true,
    "es6": true
  },
  "rules": {
    "comma-dangle": 0
  }
}
```

**Comment by sfabrizio** [comment]
thanks, this is done,
